apiVersion: v1
kind: Service
metadata:
  name: why-backend
  namespace: why
  labels:
    app: why-backend
spec:
  selector:
    app: why-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
