apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-gateway
  namespace: flux-system
spec:
  interval: 1h
  path: ./traefik-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: gateway-api
    - name: traefik
  wait: true
  timeout: 10m
