a iVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: why
  namespace: flux-system
spec:
  interval: 1h
  path: ./why
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
    - name: traefik-gateway
  wait: true
  timeout: 10m
