apiVersion: v1
kind: Service
metadata:
  name: why-frontend
  namespace: why
  labels:
    app: why-frontend
spec:
  selector:
    app: why-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
