apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - minio/deployment.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - routes/httproute-backend.yaml
  - routes/httproute-frontend.yaml
