apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-dashboards-flux-kustomization.yaml
  - namespaces.yaml
  - repositories.yaml
  - infrastructure-flux-kustomization.yaml
  - apps-flux-kustomization.yaml
  - traefik-flux-kustomization.yaml
  - cert-manager-flux-kustomization.yaml
  - external-secrets-flux-kustomization.yaml
  - metrics-server-flux-kustomization.yaml
  - why-flux-kustomization.yaml
