apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager
  - external-secrets
  - gateway-api
  - traefik
  - traefik-gateway
  - metrics-server
