apiVersion: v1
kind: Service
metadata:
  name: why-postgres
  namespace: why
spec:
  selector:
    app: why-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP
  clusterIP: None
